production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: biopartsdb_production
  pool: 5
  username: root
  password: d.748563*p
  host: db1.c1gnp09t5eej.us-east-1.rds.amazonaws.com
